[tools]
node = '24'
pnpm = '11'
go = '1.26.4'
"go:github.com/wailsapp/wails/v2/cmd/wails" = "v2.12.0"

[env]
NODE_ENV = 'development'

[tasks.dev]
run = 'wails dev'

[tasks.init]
run = 'mkdir -p ./db && test -f ./db/sqlite.db || touch ./db/sqlite.db'
run_windows = 'powershell  -Command "if (-not (Test-Path db)) { New-Item -ItemType Directory -Path db -Force | Out-Null }; if (-not (Test-Path db/sqlite.db)) { New-Item -ItemType File -Path db/sqlite.db -Force | Out-Null }"'
description = "Create db directory and sqlite.db if they don't exist."

[tasks.schema]
run = 'sqlite3 ./db/sqlite.db .schema > ./db/schema/schema.sql'
description = "Export current database schema to schema.sql."
